### ISSUE TITLE
feat: add the ability for Jaeger to authenticate in ydb using the static iam key

### ISSUE THREAD

**Issue by gingersamurai** [ydb-platform/jaeger-ydb-store#48]
# Feature Request

The key can be obtained by the command:

```
yc iam key create \
  --service-account-name <имя сервисного аккаунта для Ingress-контроллера> \
  --output sa-key.json
```

and mounts as a secret
For example, as in external-secrets is done https://external-secrets.io/v0.5.7/provider-yandex-lockbox/

```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
spec:
  provider:
    yandexlockbox:
      auth:
        authorizedKeySecretRef:
          name: yc-auth
          key: authorized-key
```
